name = "npflared"
main = "src/index.ts"
compatibility_date = "2024-11-24"

compatibility_flags = [ "nodejs_compat" ]

[vars]
FALLBACK_REGISTRY_ENDPOINT = "https://registry.npmjs.org"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "BUCKET_NAME"

[[d1_databases]]
binding = "DB"
database_name = "D1_DATABASE_NAME"
database_id = "D1_DATABASE_ID"
